export const categoriesMap = {"category":{"/":{"path":"/category/","map":{"Guide":{"path":"/category/guide/","indexes":[0,1,2,3,4,5]},"Cherry":{"path":"/category/cherry/","indexes":[6]},"Dragon Fruit":{"path":"/category/dragon-fruit/","indexes":[7]},"Fruit":{"path":"/category/fruit/","indexes":[8,7,9,10,11,12]},"Strawberry":{"path":"/category/strawberry/","indexes":[8]},"Vegetable":{"path":"/category/vegetable/","indexes":[13]},"Apple":{"path":"/category/apple/","indexes":[11,12,14,15]},"Banana":{"path":"/category/banana/","indexes":[16,17,9,10]}}},"/zh/":{"path":"/zh/category/","map":{"使用指南":{"path":"/zh/category/使用指南/","indexes":[18,19,20,21,22]},"指南":{"path":"/zh/category/指南/","indexes":[23]},"樱桃":{"path":"/zh/category/樱桃/","indexes":[24]},"火龙果":{"path":"/zh/category/火龙果/","indexes":[25]},"水果":{"path":"/zh/category/水果/","indexes":[26,25,27,28,29,30]},"草莓":{"path":"/zh/category/草莓/","indexes":[26]},"蔬菜":{"path":"/zh/category/蔬菜/","indexes":[31]},"苹果":{"path":"/zh/category/苹果/","indexes":[29,30,32,33]},"香蕉":{"path":"/zh/category/香蕉/","indexes":[34,35,27,28]}}}},"tag":{"/":{"path":"/tag/","map":{"disable":{"path":"/tag/disable/","indexes":[1]},"encryption":{"path":"/tag/encryption/","indexes":[2]},"Layout":{"path":"/tag/layout/","indexes":[3]},"Markdown":{"path":"/tag/markdown/","indexes":[4]},"Page config":{"path":"/tag/page-config/","indexes":[0]},"Guide":{"path":"/tag/guide/","indexes":[0]},"red":{"path":"/tag/red/","indexes":[13,8,7,6,11,12,14,15]},"small":{"path":"/tag/small/","indexes":[8,6]},"round":{"path":"/tag/round/","indexes":[13,6,11,12,14,15]},"big":{"path":"/tag/big/","indexes":[7,11,12,14,15]},"yellow":{"path":"/tag/yellow/","indexes":[16,17,9,10]},"curly":{"path":"/tag/curly/","indexes":[16,17,9,10]},"long":{"path":"/tag/long/","indexes":[16,17,9,10]}}},"/zh/":{"path":"/zh/tag/","map":{"禁用":{"path":"/zh/tag/禁用/","indexes":[19]},"加密":{"path":"/zh/tag/加密/","indexes":[20]},"布局":{"path":"/zh/tag/布局/","indexes":[23]},"Markdown":{"path":"/zh/tag/markdown/","indexes":[21]},"页面配置":{"path":"/zh/tag/页面配置/","indexes":[18]},"使用指南":{"path":"/zh/tag/使用指南/","indexes":[18]},"红":{"path":"/zh/tag/红/","indexes":[31,26,25,24,29,30,32,33]},"小":{"path":"/zh/tag/小/","indexes":[26,24]},"圆":{"path":"/zh/tag/圆/","indexes":[31,24,29,30,32,33]},"大":{"path":"/zh/tag/大/","indexes":[25,29,30,32,33]},"黄":{"path":"/zh/tag/黄/","indexes":[34,35,27,28]},"弯曲的":{"path":"/zh/tag/弯曲的/","indexes":[34,35,27,28]},"长":{"path":"/zh/tag/长/","indexes":[34,35,27,28]}}}}};

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept();
  if (__VUE_HMR_RUNTIME__.updateBlogCategory)
    __VUE_HMR_RUNTIME__.updateBlogCategory(categoriesMap);
}

if (import.meta.hot)
  import.meta.hot.accept(({ categoriesMap }) => {
    __VUE_HMR_RUNTIME__.updateBlogCategory(categoriesMap);
  });

