export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/intro.html.js"), meta: {"v":"/assets/images/cover3.jpg","e":"\n<p>Place your introduction and profile here.</p>\n","y":"a","t":"Intro Page","i":"circle-info"} }],
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/index.html.js"), meta: {"y":"h","t":"Home","i":"home"} }],
  ["/zh/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/intro.html.js"), meta: {"v":"/assets/images/cover3.jpg","e":"\n<p>将你的个人介绍和档案放置在此处。</p>\n","y":"a","t":"介绍页","i":"circle-info"} }],
  ["/zh/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/index.html.js"), meta: {"y":"h","t":"home","i":"home"} }],
  ["/posts/cherry.html", { loader: () => import(/* webpackChunkName: "cherry.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/cherry.html.js"), meta: {"d":1641686400000,"l":"January 9, 2022","c":["Cherry"],"g":["red","small","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","y":"a","t":"Cherry","i":"pen-to-square"} }],
  ["/posts/dragonfruit.html", { loader: () => import(/* webpackChunkName: "dragonfruit.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/dragonfruit.html.js"), meta: {"d":1641772800000,"l":"January 10, 2022","c":["Dragon Fruit","Fruit"],"g":["red","big"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","y":"a","t":"Dragon Fruit","i":"pen-to-square"} }],
  ["/posts/strawberry.html", { loader: () => import(/* webpackChunkName: "strawberry.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/strawberry.html.js"), meta: {"d":1641859200000,"l":"January 11, 2022","c":["Fruit","Strawberry"],"g":["red","small"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","y":"a","t":"Strawberry","i":"pen-to-square"} }],
  ["/posts/tomato.html", { loader: () => import(/* webpackChunkName: "tomato.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/tomato.html.js"), meta: {"d":1641945600000,"l":"January 12, 2022","c":["Vegetable"],"g":["red","round"],"u":true,"v":"/assets/images/cover2.jpg","e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","y":"a","t":"Tomato","i":"pen-to-square"} }],
  ["/zh/posts/cherry.html", { loader: () => import(/* webpackChunkName: "cherry.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/cherry.html.js"), meta: {"d":1641686400000,"l":"2022年1月9日","c":["樱桃"],"g":["红","小","圆"],"e":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"樱桃","i":"pen-to-square"} }],
  ["/zh/posts/dragonfruit.html", { loader: () => import(/* webpackChunkName: "dragonfruit.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/dragonfruit.html.js"), meta: {"d":1641772800000,"l":"2022年1月10日","c":["火龙果","水果"],"g":["红","大"],"e":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"火龙果","i":"pen-to-square"} }],
  ["/zh/posts/strawberry.html", { loader: () => import(/* webpackChunkName: "strawberry.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/strawberry.html.js"), meta: {"d":1641859200000,"l":"2022年1月11日","c":["水果","草莓"],"g":["红","小"],"e":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"草莓","i":"pen-to-square"} }],
  ["/zh/posts/tomato.html", { loader: () => import(/* webpackChunkName: "tomato.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/tomato.html.js"), meta: {"d":1641945600000,"l":"2022年1月12日","c":["蔬菜"],"g":["红","圆"],"u":true,"v":"/assets/images/cover2.jpg","e":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"番茄","i":"pen-to-square"} }],
  ["/posts/apple/1.html", { loader: () => import(/* webpackChunkName: "1.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/apple/1.html.js"), meta: {"d":1640995200000,"l":"January 1, 2022","c":["Apple"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","y":"a","t":"Apple 1","i":"pen-to-square"} }],
  ["/posts/apple/2.html", { loader: () => import(/* webpackChunkName: "2.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/apple/2.html.js"), meta: {"d":1641081600000,"l":"January 2, 2022","c":["Apple"],"g":["red","big","round"],"e":"\n<p>A apple article being stared.</p>\n","y":"a","t":"Apple 2","i":"pen-to-square"} }],
  ["/posts/apple/3.html", { loader: () => import(/* webpackChunkName: "3.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/apple/3.html.js"), meta: {"d":1641168000000,"l":"January 3, 2022","c":["Apple","Fruit"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","y":"a","t":"Apple 3","i":"pen-to-square"} }],
  ["/posts/apple/4.html", { loader: () => import(/* webpackChunkName: "4.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/apple/4.html.js"), meta: {"d":1641254400000,"l":"January 4, 2022","c":["Apple","Fruit"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","y":"a","t":"Apple 4","i":"pen-to-square"} }],
  ["/posts/banana/1.html", { loader: () => import(/* webpackChunkName: "1.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/banana/1.html.js"), meta: {"d":1641340800000,"l":"January 5, 2022","c":["Banana","Fruit"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","y":"a","t":"Banana 1","i":"pen-to-square"} }],
  ["/posts/banana/2.html", { loader: () => import(/* webpackChunkName: "2.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/banana/2.html.js"), meta: {"d":1641427200000,"l":"January 6, 2022","c":["Banana","Fruit"],"g":["yellow","curly","long"],"e":"\n<p>A banana article being stared with number <code>10</code>.</p>\n","y":"a","t":"Banana 2","i":"pen-to-square"} }],
  ["/posts/banana/3.html", { loader: () => import(/* webpackChunkName: "3.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/banana/3.html.js"), meta: {"d":1641513600000,"l":"January 7, 2022","c":["Banana"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","y":"a","t":"Banana 3","i":"pen-to-square"} }],
  ["/posts/banana/4.html", { loader: () => import(/* webpackChunkName: "4.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/banana/4.html.js"), meta: {"d":1641600000000,"l":"January 8, 2022","c":["Banana"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","y":"a","t":"Banana 4","i":"pen-to-square"} }],
  ["/zh/posts/apple/1.html", { loader: () => import(/* webpackChunkName: "1.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/apple/1.html.js"), meta: {"d":1640995200000,"l":"2022年1月1日","c":["苹果"],"g":["红","大","圆"],"e":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"苹果 1","i":"pen-to-square"} }],
  ["/zh/posts/apple/2.html", { loader: () => import(/* webpackChunkName: "2.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/apple/2.html.js"), meta: {"d":1641081600000,"l":"2022年1月2日","c":["苹果"],"g":["红","大","圆"],"e":"\n<p>一个被星标了的苹果文章。</p>\n","y":"a","t":"苹果 2","i":"pen-to-square"} }],
  ["/zh/posts/apple/3.html", { loader: () => import(/* webpackChunkName: "3.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/apple/3.html.js"), meta: {"d":1641168000000,"l":"2022年1月3日","c":["苹果","水果"],"g":["红","大","圆"],"e":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"苹果 3","i":"pen-to-square"} }],
  ["/zh/posts/apple/4.html", { loader: () => import(/* webpackChunkName: "4.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/apple/4.html.js"), meta: {"d":1641254400000,"l":"2022年1月4日","c":["苹果","水果"],"g":["红","大","圆"],"e":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"苹果 4","i":"pen-to-square"} }],
  ["/zh/posts/banana/1.html", { loader: () => import(/* webpackChunkName: "1.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/banana/1.html.js"), meta: {"d":1641340800000,"l":"2022年1月5日","c":["香蕉","水果"],"g":["黄","弯曲的","长"],"e":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"香蕉 1","i":"pen-to-square"} }],
  ["/zh/posts/banana/2.html", { loader: () => import(/* webpackChunkName: "2.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/banana/2.html.js"), meta: {"d":1641427200000,"l":"2022年1月6日","c":["香蕉","水果"],"g":["黄","弯曲的","长"],"e":"\n<p>一个被数字 <code>10</code> 星标了的香蕉文章。</p>\n","y":"a","t":"香蕉 2","i":"pen-to-square"} }],
  ["/zh/posts/banana/3.html", { loader: () => import(/* webpackChunkName: "3.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/banana/3.html.js"), meta: {"d":1641513600000,"l":"2022年1月7日","c":["香蕉"],"g":["黄","弯曲的","长"],"e":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"香蕉 3","i":"pen-to-square"} }],
  ["/zh/posts/banana/4.html", { loader: () => import(/* webpackChunkName: "4.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/banana/4.html.js"), meta: {"d":1641600000000,"l":"2022年1月8日","c":["香蕉"],"g":["黄","弯曲的","长"],"e":"\n<h2>标题 2</h2>\n<p>这里是内容。</p>\n<h3>标题 3</h3>\n<p>这里是内容。</p>\n","y":"a","t":"香蕉 4","i":"pen-to-square"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/404.html.js"), meta: {"y":"p","t":""} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/index.html.js"), meta: {"y":"p","t":"Posts"} }],
  ["/zh/posts/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/index.html.js"), meta: {"y":"p","t":"Posts"} }],
  ["/posts/apple/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/apple/index.html.js"), meta: {"y":"p","t":"Apple"} }],
  ["/posts/banana/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/posts/banana/index.html.js"), meta: {"y":"p","t":"Banana"} }],
  ["/zh/posts/apple/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/apple/index.html.js"), meta: {"y":"p","t":"Apple"} }],
  ["/zh/posts/banana/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/posts/banana/index.html.js"), meta: {"y":"p","t":"Banana"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"y":"p","t":"Category","I":false} }],
  ["/category/cherry/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/category/cherry/index.html.js"), meta: {"y":"p","t":"Cherry Category","I":false} }],
  ["/category/dragon-fruit/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/category/dragon-fruit/index.html.js"), meta: {"y":"p","t":"Dragon Fruit Category","I":false} }],
  ["/category/fruit/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/category/fruit/index.html.js"), meta: {"y":"p","t":"Fruit Category","I":false} }],
  ["/category/strawberry/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/category/strawberry/index.html.js"), meta: {"y":"p","t":"Strawberry Category","I":false} }],
  ["/category/vegetable/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/category/vegetable/index.html.js"), meta: {"y":"p","t":"Vegetable Category","I":false} }],
  ["/category/apple/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/category/apple/index.html.js"), meta: {"y":"p","t":"Apple Category","I":false} }],
  ["/category/banana/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/category/banana/index.html.js"), meta: {"y":"p","t":"Banana Category","I":false} }],
  ["/zh/category/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/category/index.html.js"), meta: {"y":"p","t":"分类","I":false} }],
  ["/zh/category/%E6%A8%B1%E6%A1%83/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/category/樱桃/index.html.js"), meta: {"y":"p","t":"樱桃 分类","I":false} }],
  ["/zh/category/%E7%81%AB%E9%BE%99%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/category/火龙果/index.html.js"), meta: {"y":"p","t":"火龙果 分类","I":false} }],
  ["/zh/category/%E6%B0%B4%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/category/水果/index.html.js"), meta: {"y":"p","t":"水果 分类","I":false} }],
  ["/zh/category/%E8%8D%89%E8%8E%93/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/category/草莓/index.html.js"), meta: {"y":"p","t":"草莓 分类","I":false} }],
  ["/zh/category/%E8%94%AC%E8%8F%9C/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/category/蔬菜/index.html.js"), meta: {"y":"p","t":"蔬菜 分类","I":false} }],
  ["/zh/category/%E8%8B%B9%E6%9E%9C/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/category/苹果/index.html.js"), meta: {"y":"p","t":"苹果 分类","I":false} }],
  ["/zh/category/%E9%A6%99%E8%95%89/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/category/香蕉/index.html.js"), meta: {"y":"p","t":"香蕉 分类","I":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"y":"p","t":"Tag","I":false} }],
  ["/tag/red/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/tag/red/index.html.js"), meta: {"y":"p","t":"Tag: red","I":false} }],
  ["/tag/small/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/tag/small/index.html.js"), meta: {"y":"p","t":"Tag: small","I":false} }],
  ["/tag/round/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/tag/round/index.html.js"), meta: {"y":"p","t":"Tag: round","I":false} }],
  ["/tag/big/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/tag/big/index.html.js"), meta: {"y":"p","t":"Tag: big","I":false} }],
  ["/tag/yellow/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/tag/yellow/index.html.js"), meta: {"y":"p","t":"Tag: yellow","I":false} }],
  ["/tag/curly/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/tag/curly/index.html.js"), meta: {"y":"p","t":"Tag: curly","I":false} }],
  ["/tag/long/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/tag/long/index.html.js"), meta: {"y":"p","t":"Tag: long","I":false} }],
  ["/zh/tag/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/tag/index.html.js"), meta: {"y":"p","t":"标签","I":false} }],
  ["/zh/tag/%E7%BA%A2/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/tag/红/index.html.js"), meta: {"y":"p","t":"标签: 红","I":false} }],
  ["/zh/tag/%E5%B0%8F/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/tag/小/index.html.js"), meta: {"y":"p","t":"标签: 小","I":false} }],
  ["/zh/tag/%E5%9C%86/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/tag/圆/index.html.js"), meta: {"y":"p","t":"标签: 圆","I":false} }],
  ["/zh/tag/%E5%A4%A7/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/tag/大/index.html.js"), meta: {"y":"p","t":"标签: 大","I":false} }],
  ["/zh/tag/%E9%BB%84/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/tag/黄/index.html.js"), meta: {"y":"p","t":"标签: 黄","I":false} }],
  ["/zh/tag/%E5%BC%AF%E6%9B%B2%E7%9A%84/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/tag/弯曲的/index.html.js"), meta: {"y":"p","t":"标签: 弯曲的","I":false} }],
  ["/zh/tag/%E9%95%BF/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/tag/长/index.html.js"), meta: {"y":"p","t":"标签: 长","I":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"y":"p","t":"Articles","I":false} }],
  ["/zh/article/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/article/index.html.js"), meta: {"y":"p","t":"文章","I":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"y":"p","t":"Star","I":false} }],
  ["/zh/star/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/star/index.html.js"), meta: {"y":"p","t":"星标","I":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"y":"p","t":"Timeline","I":false} }],
  ["/zh/timeline/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/LCY/Documents/GitHub/vue/src/.vuepress/.temp/pages/zh/timeline/index.html.js"), meta: {"y":"p","t":"时间轴","I":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
